<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="docs\**" />
    <EmbeddedResource Remove="docs\**" />
    <None Remove="docs\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="glc2d\README.md" />
    <None Remove="README.md" />
  </ItemGroup>

  <ItemGroup>
    <None Include="waksmash.sln" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="glc2dcsharp" Version="0.1.0.7" />
    <PackageReference Include="NAudio" Version="3.0.1" />
    <PackageReference Include="Vortice.Direct2D1" Version="3.8.3" />
    <PackageReference Include="Vortice.WinForms" Version="3.8.3" />
    <PackageReference Include="Vortice.XAudio2" Version="3.8.3" />
    <PackageReference Include="Vortice.XInput" Version="3.8.3" />
  </ItemGroup>

<ItemGroup>
  <None Update="resource\**\*">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
  </None>
</ItemGroup>

</Project>
