<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="glc2dcsharp" Version="0.1.0.7" />
    <PackageReference Include="Vortice.WinForms" Version="3.8.3" />
    <PackageReference Include="Vortice.XAudio2" Version="3.8.3" />
    <PackageReference Include="Vortice.XInput" Version="3.8.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="resource\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>